version: 1.0.{build}
image: macOS
build_script:
- sh: PERL_MM_USE_DEFAULT=1 cpan App::cpanminus && /Users/appveyor/perl5/bin/cpanm --installdeps . && perl Makefile.PL && make
test_script:
- sh: make test
